system:
  Version: 1.0.0
  env: debug
  httpPort: localhost:3000
  host: localhost
  upLoadMode: Oss
  Domain: xxxxx.com

mysql:
  username: user
  password: password
  host: localhost
  port: 3307
  dbName: mall
  charset: utf8mb4
  parseTime: True
  Loc: Local


Zap:
    prefix: wxapp
    level: debug
    director: ./pkg/log/logs
    encoderLevel: LowercaseColorLevelEncoder
    maxAge: 7
    showLine: true
    logInConsole: true
    encoder: console
    maxSize: 600
    maxBackups: 5
    compress: true


